services:
  frontend:
    build:
      context: .
      target: frontend
      args:
        - CHOKIDAR_USEPOLLING=true
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
        - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
        - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
        - LINKEDIN_REDIRECT_URI=${LINKEDIN_REDIRECT_URI}
        - VERTEX_AI_API_KEY=${VERTEX_AI_API_KEY}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - LINKEDIN_REDIRECT_URI=${LINKEDIN_REDIRECT_URI}
      - VERTEX_AI_API_KEY=${VERTEX_AI_API_KEY}
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      target: backend
      args:
        - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - VITE_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - VITE_GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
        - VITE_LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
        - VITE_LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
        - VITE_LINKEDIN_REDIRECT_URI=${LINKEDIN_REDIRECT_URI}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - LINKEDIN_REDIRECT_URI=${LINKEDIN_REDIRECT_URI}
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./portiq:/app/portiq
      - ./portiq_server:/app/portiq_server
      - ./react_server:/app/react_server
      - ./manage.py:/app/manage.py

volumes:
  frontend_node_modules:
  frontend_dist:
  backend_pycache:
  backend_migrations:
