services:
  frontend:
    build:
      context: .
      target: frontend-dev
    ports:
      - "3000:3000"
    command: pnpm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for development
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      # Exclude node_modules to prevent host/container conflicts
      - frontend_node_modules:/app/node_modules
      # Exclude build artifacts
      - frontend_dist:/app/dist

  backend:
    build:
      context: .
      target: backend
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount Django project files
      - ./portiq:/app/portiq
      - ./portiq_server:/app/portiq_server
      - ./react_server:/app/react_server
      - ./manage.py:/app/manage.py
      # Exclude Python cache files
      - backend_pycache:/app/__pycache__
      - backend_migrations:/app/portiq_server/migrations

volumes:
  # Define named volumes
  frontend_node_modules:
  frontend_dist:
  backend_pycache:
  backend_migrations:
