/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeType
 */
export interface CodeType {
    /**
     * 
     * @type {string}
     * @memberof CodeType
     */
    html: string;
    /**
     * 
     * @type {string}
     * @memberof CodeType
     */
    css: string;
    /**
     * 
     * @type {string}
     * @memberof CodeType
     */
    js: string;
}

/**
 * Check if a given object implements the CodeType interface.
 */
export function instanceOfCodeType(value: object): value is CodeType {
    if (!('html' in value) || value['html'] === undefined) return false;
    if (!('css' in value) || value['css'] === undefined) return false;
    if (!('js' in value) || value['js'] === undefined) return false;
    return true;
}

export function CodeTypeFromJSON(json: any): CodeType {
    return CodeTypeFromJSONTyped(json, false);
}

export function CodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeType {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'],
        'css': json['css'],
        'js': json['js'],
    };
}

export function CodeTypeToJSON(json: any): CodeType {
    return CodeTypeToJSONTyped(json, false);
}

export function CodeTypeToJSONTyped(value?: CodeType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html': value['html'],
        'css': value['css'],
        'js': value['js'],
    };
}

