/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Code
 */
export interface Code {
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    html: string;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    css: string;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    js: string;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Code
     */
    id: number;
}

/**
 * Check if a given object implements the Code interface.
 */
export function instanceOfCode(value: object): value is Code {
    if (!('html' in value) || value['html'] === undefined) return false;
    if (!('css' in value) || value['css'] === undefined) return false;
    if (!('js' in value) || value['js'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CodeFromJSON(json: any): Code {
    return CodeFromJSONTyped(json, false);
}

export function CodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Code {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'],
        'css': json['css'],
        'js': json['js'],
        'title': json['title'],
        'id': json['id'],
    };
}

export function CodeToJSON(json: any): Code {
    return CodeToJSONTyped(json, false);
}

export function CodeToJSONTyped(value?: Code | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html': value['html'],
        'css': value['css'],
        'js': value['js'],
        'title': value['title'],
        'id': value['id'],
    };
}

