/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Development
 */
export interface Development {
    /**
     * 
     * @type {any}
     * @memberof Development
     */
    groupData: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof Development
     */
    createFullTemplate: boolean;
}

/**
 * Check if a given object implements the Development interface.
 */
export function instanceOfDevelopment(value: object): value is Development {
    if (!('groupData' in value) || value['groupData'] === undefined) return false;
    if (!('createFullTemplate' in value) || value['createFullTemplate'] === undefined) return false;
    return true;
}

export function DevelopmentFromJSON(json: any): Development {
    return DevelopmentFromJSONTyped(json, false);
}

export function DevelopmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Development {
    if (json == null) {
        return json;
    }
    return {
        
        'groupData': json['groupData'],
        'createFullTemplate': json['createFullTemplate'],
    };
}

export function DevelopmentToJSON(json: any): Development {
    return DevelopmentToJSONTyped(json, false);
}

export function DevelopmentToJSONTyped(value?: Development | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupData': value['groupData'],
        'createFullTemplate': value['createFullTemplate'],
    };
}

