/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    instanceOfBlankEnum,
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { TypeEnum } from './TypeEnum';
import {
    instanceOfTypeEnum,
    TypeEnumFromJSON,
    TypeEnumFromJSONTyped,
    TypeEnumToJSON,
} from './TypeEnum';

/**
 * @type EducationType
 * 
 * @export
 */
export type EducationType = BlankEnum | TypeEnum;

export function EducationTypeFromJSON(json: any): EducationType {
    return EducationTypeFromJSONTyped(json, false);
}

export function EducationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationType {
    if (json == null) {
        return json;
    }
    if (instanceOfBlankEnum(json)) {
        return BlankEnumFromJSONTyped(json, true);
    }
    if (instanceOfTypeEnum(json)) {
        return TypeEnumFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EducationTypeToJSON(json: any): any {
    return EducationTypeToJSONTyped(json, false);
}

export function EducationTypeToJSONTyped(value?: EducationType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBlankEnum(value)) {
        return BlankEnumToJSON(value as BlankEnum);
    }
    if (instanceOfTypeEnum(value)) {
        return TypeEnumToJSON(value as TypeEnum);
    }

    return {};
}

