/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinkedinData
 */
export interface GetLinkedinData {
    /**
     * 
     * @type {string}
     * @memberof GetLinkedinData
     */
    sub?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetLinkedinData
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetLinkedinData
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GetLinkedinData
     */
    locale: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof GetLinkedinData
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinkedinData
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinkedinData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinkedinData
     */
    picture?: string;
}

/**
 * Check if a given object implements the GetLinkedinData interface.
 */
export function instanceOfGetLinkedinData(value: object): value is GetLinkedinData {
    if (!('locale' in value) || value['locale'] === undefined) return false;
    return true;
}

export function GetLinkedinDataFromJSON(json: any): GetLinkedinData {
    return GetLinkedinDataFromJSONTyped(json, false);
}

export function GetLinkedinDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinkedinData {
    if (json == null) {
        return json;
    }
    return {
        
        'sub': json['sub'] == null ? undefined : json['sub'],
        'emailVerified': json['email_verified'] == null ? undefined : json['email_verified'],
        'name': json['name'] == null ? undefined : json['name'],
        'locale': json['locale'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'picture': json['picture'] == null ? undefined : json['picture'],
    };
}

export function GetLinkedinDataToJSON(json: any): GetLinkedinData {
    return GetLinkedinDataToJSONTyped(json, false);
}

export function GetLinkedinDataToJSONTyped(value?: GetLinkedinData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sub': value['sub'],
        'email_verified': value['emailVerified'],
        'name': value['name'],
        'locale': value['locale'],
        'given_name': value['givenName'],
        'family_name': value['familyName'],
        'email': value['email'],
        'picture': value['picture'],
    };
}

