/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSelectedComponents
 */
export interface GetSelectedComponents {
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idUserInfoDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idSkillDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idLanguageDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idProjectDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idCertificateDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idEducationDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idHobbyDevelopment?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetSelectedComponents
     */
    idOtherDevelopment?: number | null;
}

/**
 * Check if a given object implements the GetSelectedComponents interface.
 */
export function instanceOfGetSelectedComponents(value: object): value is GetSelectedComponents {
    return true;
}

export function GetSelectedComponentsFromJSON(json: any): GetSelectedComponents {
    return GetSelectedComponentsFromJSONTyped(json, false);
}

export function GetSelectedComponentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSelectedComponents {
    if (json == null) {
        return json;
    }
    return {
        
        'idUserInfoDevelopment': json['id_user_info_development'] == null ? undefined : json['id_user_info_development'],
        'idSkillDevelopment': json['id_skill_development'] == null ? undefined : json['id_skill_development'],
        'idLanguageDevelopment': json['id_language_development'] == null ? undefined : json['id_language_development'],
        'idProjectDevelopment': json['id_project_development'] == null ? undefined : json['id_project_development'],
        'idCertificateDevelopment': json['id_certificate_development'] == null ? undefined : json['id_certificate_development'],
        'idEducationDevelopment': json['id_education_development'] == null ? undefined : json['id_education_development'],
        'idHobbyDevelopment': json['id_hobby_development'] == null ? undefined : json['id_hobby_development'],
        'idOtherDevelopment': json['id_other_development'] == null ? undefined : json['id_other_development'],
    };
}

export function GetSelectedComponentsToJSON(json: any): GetSelectedComponents {
    return GetSelectedComponentsToJSONTyped(json, false);
}

export function GetSelectedComponentsToJSONTyped(value?: GetSelectedComponents | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id_user_info_development': value['idUserInfoDevelopment'],
        'id_skill_development': value['idSkillDevelopment'],
        'id_language_development': value['idLanguageDevelopment'],
        'id_project_development': value['idProjectDevelopment'],
        'id_certificate_development': value['idCertificateDevelopment'],
        'id_education_development': value['idEducationDevelopment'],
        'id_hobby_development': value['idHobbyDevelopment'],
        'id_other_development': value['idOtherDevelopment'],
    };
}

