/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubRequest
 */
export interface GithubRequest {
    /**
     * 
     * @type {string}
     * @memberof GithubRequest
     */
    username: string;
}

/**
 * Check if a given object implements the GithubRequest interface.
 */
export function instanceOfGithubRequest(value: object): value is GithubRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function GithubRequestFromJSON(json: any): GithubRequest {
    return GithubRequestFromJSONTyped(json, false);
}

export function GithubRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function GithubRequestToJSON(json: any): GithubRequest {
    return GithubRequestToJSONTyped(json, false);
}

export function GithubRequestToJSONTyped(value?: GithubRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

