/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageUploadResponse
 */
export interface ImageUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof ImageUploadResponse
     */
    publicId: string;
    /**
     * 
     * @type {string}
     * @memberof ImageUploadResponse
     */
    url: string;
}

/**
 * Check if a given object implements the ImageUploadResponse interface.
 */
export function instanceOfImageUploadResponse(value: object): value is ImageUploadResponse {
    if (!('publicId' in value) || value['publicId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ImageUploadResponseFromJSON(json: any): ImageUploadResponse {
    return ImageUploadResponseFromJSONTyped(json, false);
}

export function ImageUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'publicId': json['public_id'],
        'url': json['url'],
    };
}

export function ImageUploadResponseToJSON(json: any): ImageUploadResponse {
    return ImageUploadResponseToJSONTyped(json, false);
}

export function ImageUploadResponseToJSONTyped(value?: ImageUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_id': value['publicId'],
        'url': value['url'],
    };
}

