/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EducationType } from './EducationType';
import {
    EducationTypeFromJSON,
    EducationTypeFromJSONTyped,
    EducationTypeToJSON,
    EducationTypeToJSONTyped,
} from './EducationType';

/**
 * 
 * @export
 * @interface PatchedEducation
 */
export interface PatchedEducation {
    /**
     * 
     * @type {number}
     * @memberof PatchedEducation
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedEducation
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEducation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEducation
     */
    location?: string;
    /**
     * 
     * @type {EducationType}
     * @memberof PatchedEducation
     */
    type?: EducationType | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEducation
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEducation
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedEducation
     */
    link?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEducation
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the PatchedEducation interface.
 */
export function instanceOfPatchedEducation(value: object): value is PatchedEducation {
    return true;
}

export function PatchedEducationFromJSON(json: any): PatchedEducation {
    return PatchedEducationFromJSONTyped(json, false);
}

export function PatchedEducationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEducation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'type': json['type'] == null ? undefined : EducationTypeFromJSON(json['type']),
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'link': json['link'] == null ? undefined : json['link'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PatchedEducationToJSON(json: any): PatchedEducation {
    return PatchedEducationToJSONTyped(json, false);
}

export function PatchedEducationToJSONTyped(value?: Omit<PatchedEducation, 'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'location': value['location'],
        'type': EducationTypeToJSON(value['type']),
        'start_date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'link': value['link'],
    };
}

