/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCertificate
 */
export interface PatchedCertificate {
    /**
     * 
     * @type {number}
     * @memberof PatchedCertificate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedCertificate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCertificate
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCertificate
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCertificate
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedCertificate
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedCertificate
     */
    link?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCertificate
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the PatchedCertificate interface.
 */
export function instanceOfPatchedCertificate(value: object): value is PatchedCertificate {
    return true;
}

export function PatchedCertificateFromJSON(json: any): PatchedCertificate {
    return PatchedCertificateFromJSONTyped(json, false);
}

export function PatchedCertificateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCertificate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'location': json['location'] == null ? undefined : json['location'],
        'link': json['link'] == null ? undefined : json['link'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PatchedCertificateToJSON(json: any): PatchedCertificate {
    return PatchedCertificateToJSONTyped(json, false);
}

export function PatchedCertificateToJSONTyped(value?: Omit<PatchedCertificate, 'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'location': value['location'],
        'link': value['link'],
    };
}

