/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PatchedUser
 */
export interface PatchedUser {
  /**
   *
   * @type {number}
   * @memberof PatchedUser
   */
  readonly id?: number;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  token?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  phoneNumer?: string | null;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  address?: string | null;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  city?: string | null;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  state?: string | null;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  zipCode?: string | null;
  /**
   *
   * @type {string}
   * @memberof PatchedUser
   */
  country?: string | null;
  /**
   *
   * @type {Date}
   * @memberof PatchedUser
   */
  readonly createdAt?: Date;
}

/**
 * Check if a given object implements the PatchedUser interface.
 */
export function instanceOfPatchedUser() {
  return true;
}

export function PatchedUserFromJSON(json: any): PatchedUser {
  return PatchedUserFromJSONTyped(json);
}

export function PatchedUserFromJSONTyped(json: any): PatchedUser {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    firstName: json["first_name"] == null ? undefined : json["first_name"],
    lastName: json["last_name"] == null ? undefined : json["last_name"],
    email: json["email"] == null ? undefined : json["email"],
    token: json["token"] == null ? undefined : json["token"],
    phoneNumer: json["phone_numer"] == null ? undefined : json["phone_numer"],
    address: json["address"] == null ? undefined : json["address"],
    city: json["city"] == null ? undefined : json["city"],
    state: json["state"] == null ? undefined : json["state"],
    zipCode: json["zip_code"] == null ? undefined : json["zip_code"],
    country: json["country"] == null ? undefined : json["country"],
    createdAt:
      json["created_at"] == null ? undefined : new Date(json["created_at"]),
  };
}

export function PatchedUserToJSON(json: any): PatchedUser {
  return PatchedUserToJSONTyped(json);
}

export function PatchedUserToJSONTyped(
  value?: Omit<PatchedUser, "id" | "created_at"> | null
): any {
  if (value == null) {
    return value;
  }

  return {
    first_name: value["firstName"],
    last_name: value["lastName"],
    email: value["email"],
    token: value["token"],
    phone_numer: value["phoneNumer"],
    address: value["address"],
    city: value["city"],
    state: value["state"],
    zip_code: value["zipCode"],
    country: value["country"],
  };
}
