/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostVertexAiGenerateText
 */
export interface PostVertexAiGenerateText {
    /**
     * 
     * @type {string}
     * @memberof PostVertexAiGenerateText
     */
    prompt: string;
}

/**
 * Check if a given object implements the PostVertexAiGenerateText interface.
 */
export function instanceOfPostVertexAiGenerateText(value: object): value is PostVertexAiGenerateText {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function PostVertexAiGenerateTextFromJSON(json: any): PostVertexAiGenerateText {
    return PostVertexAiGenerateTextFromJSONTyped(json, false);
}

export function PostVertexAiGenerateTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVertexAiGenerateText {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
    };
}

export function PostVertexAiGenerateTextToJSON(json: any): PostVertexAiGenerateText {
    return PostVertexAiGenerateTextToJSONTyped(json, false);
}

export function PostVertexAiGenerateTextToJSONTyped(value?: PostVertexAiGenerateText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
    };
}

