/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutImageUpload
 */
export interface PutImageUpload {
    /**
     * 
     * @type {string}
     * @memberof PutImageUpload
     */
    image: string;
}

/**
 * Check if a given object implements the PutImageUpload interface.
 */
export function instanceOfPutImageUpload(value: object): value is PutImageUpload {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function PutImageUploadFromJSON(json: any): PutImageUpload {
    return PutImageUploadFromJSONTyped(json, false);
}

export function PutImageUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutImageUpload {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function PutImageUploadToJSON(json: any): PutImageUpload {
    return PutImageUploadToJSONTyped(json, false);
}

export function PutImageUploadToJSONTyped(value?: PutImageUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
    };
}

