/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutLinkedinData
 */
export interface PutLinkedinData {
    /**
     * 
     * @type {string}
     * @memberof PutLinkedinData
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PutLinkedinData
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PutLinkedinData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PutLinkedinData
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PutLinkedinData
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the PutLinkedinData interface.
 */
export function instanceOfPutLinkedinData(value: object): value is PutLinkedinData {
    return true;
}

export function PutLinkedinDataFromJSON(json: any): PutLinkedinData {
    return PutLinkedinDataFromJSONTyped(json, false);
}

export function PutLinkedinDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutLinkedinData {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function PutLinkedinDataToJSON(json: any): PutLinkedinData {
    return PutLinkedinDataToJSONTyped(json, false);
}

export function PutLinkedinDataToJSONTyped(value?: PutLinkedinData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'image_url': value['imageUrl'],
    };
}

