/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutSummary
 */
export interface PutSummary {
    /**
     * 
     * @type {string}
     * @memberof PutSummary
     */
    summary: string;
}

/**
 * Check if a given object implements the PutSummary interface.
 */
export function instanceOfPutSummary(value: object): value is PutSummary {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function PutSummaryFromJSON(json: any): PutSummary {
    return PutSummaryFromJSONTyped(json, false);
}

export function PutSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'],
    };
}

export function PutSummaryToJSON(json: any): PutSummary {
    return PutSummaryToJSONTyped(json, false);
}

export function PutSummaryToJSONTyped(value?: PutSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
    };
}

