/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutUserData
 */
export interface PutUserData {
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    zipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutUserData
     */
    country?: string | null;
}

/**
 * Check if a given object implements the PutUserData interface.
 */
export function instanceOfPutUserData(value: object): value is PutUserData {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function PutUserDataFromJSON(json: any): PutUserData {
    return PutUserDataFromJSONTyped(json, false);
}

export function PutUserDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutUserData {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function PutUserDataToJSON(json: any): PutUserData {
    return PutUserDataToJSONTyped(json, false);
}

export function PutUserDataToJSONTyped(value?: PutUserData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'address': value['address'],
        'city': value['city'],
        'state': value['state'],
        'zip_code': value['zipCode'],
        'country': value['country'],
    };
}

