/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseVertexAiGenerateText
 */
export interface ResponseVertexAiGenerateText {
    /**
     * 
     * @type {string}
     * @memberof ResponseVertexAiGenerateText
     */
    generatedText: string;
}

/**
 * Check if a given object implements the ResponseVertexAiGenerateText interface.
 */
export function instanceOfResponseVertexAiGenerateText(value: object): value is ResponseVertexAiGenerateText {
    if (!('generatedText' in value) || value['generatedText'] === undefined) return false;
    return true;
}

export function ResponseVertexAiGenerateTextFromJSON(json: any): ResponseVertexAiGenerateText {
    return ResponseVertexAiGenerateTextFromJSONTyped(json, false);
}

export function ResponseVertexAiGenerateTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseVertexAiGenerateText {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedText': json['generated_text'],
    };
}

export function ResponseVertexAiGenerateTextToJSON(json: any): ResponseVertexAiGenerateText {
    return ResponseVertexAiGenerateTextToJSONTyped(json, false);
}

export function ResponseVertexAiGenerateTextToJSONTyped(value?: ResponseVertexAiGenerateText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_text': value['generatedText'],
    };
}

