/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `primary_school` - Primary School
 * * `high_school` - High School
 * * `faculty` - Faculty
 * * `course` - Course
 * * `workshop` - Workshop
 * * `other` - Other
 * @export
 */
export const TypeEnum = {
    PrimarySchool: 'primary_school',
    HighSchool: 'high_school',
    Faculty: 'faculty',
    Course: 'course',
    Workshop: 'workshop',
    Other: 'other'
} as const;
export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];


export function instanceOfTypeEnum(value: any): boolean {
    for (const key in TypeEnum) {
        if (Object.prototype.hasOwnProperty.call(TypeEnum, key)) {
            if (TypeEnum[key as keyof typeof TypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TypeEnumFromJSON(json: any): TypeEnum {
    return TypeEnumFromJSONTyped(json, false);
}

export function TypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeEnum {
    return json as TypeEnum;
}

export function TypeEnumToJSON(value?: TypeEnum | null): any {
    return value as any;
}

export function TypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): TypeEnum {
    return value as TypeEnum;
}

