/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetailsUserDetailsRetrieve401Response
 */
export interface UserDetailsUserDetailsRetrieve401Response {
    /**
     * 
     * @type {string}
     * @memberof UserDetailsUserDetailsRetrieve401Response
     */
    error?: string;
}

/**
 * Check if a given object implements the UserDetailsUserDetailsRetrieve401Response interface.
 */
export function instanceOfUserDetailsUserDetailsRetrieve401Response(value: object): value is UserDetailsUserDetailsRetrieve401Response {
    return true;
}

export function UserDetailsUserDetailsRetrieve401ResponseFromJSON(json: any): UserDetailsUserDetailsRetrieve401Response {
    return UserDetailsUserDetailsRetrieve401ResponseFromJSONTyped(json, false);
}

export function UserDetailsUserDetailsRetrieve401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailsUserDetailsRetrieve401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UserDetailsUserDetailsRetrieve401ResponseToJSON(json: any): UserDetailsUserDetailsRetrieve401Response {
    return UserDetailsUserDetailsRetrieve401ResponseToJSONTyped(json, false);
}

export function UserDetailsUserDetailsRetrieve401ResponseToJSONTyped(value?: UserDetailsUserDetailsRetrieve401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

