/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserUserDetailsRetrieve200ResponseInfo } from './UserUserDetailsRetrieve200ResponseInfo';
import {
    UserUserDetailsRetrieve200ResponseInfoFromJSON,
    UserUserDetailsRetrieve200ResponseInfoFromJSONTyped,
    UserUserDetailsRetrieve200ResponseInfoToJSON,
    UserUserDetailsRetrieve200ResponseInfoToJSONTyped,
} from './UserUserDetailsRetrieve200ResponseInfo';

/**
 * 
 * @export
 * @interface UserUserDetailsRetrieve200Response
 */
export interface UserUserDetailsRetrieve200Response {
    /**
     * 
     * @type {UserUserDetailsRetrieve200ResponseInfo}
     * @memberof UserUserDetailsRetrieve200Response
     */
    info?: UserUserDetailsRetrieve200ResponseInfo;
    /**
     * 
     * @type {Array<Array<string | null>>}
     * @memberof UserUserDetailsRetrieve200Response
     */
    certificates?: Array<Array<string | null>>;
    /**
     * 
     * @type {Array<Array<string | null>>}
     * @memberof UserUserDetailsRetrieve200Response
     */
    education?: Array<Array<string | null>>;
    /**
     * 
     * @type {Array<Array<string | null>>}
     * @memberof UserUserDetailsRetrieve200Response
     */
    skills?: Array<Array<string | null>>;
    /**
     * 
     * @type {Array<Array<string | null>>}
     * @memberof UserUserDetailsRetrieve200Response
     */
    projects?: Array<Array<string | null>>;
}

/**
 * Check if a given object implements the UserUserDetailsRetrieve200Response interface.
 */
export function instanceOfUserUserDetailsRetrieve200Response(value: object): value is UserUserDetailsRetrieve200Response {
    return true;
}

export function UserUserDetailsRetrieve200ResponseFromJSON(json: any): UserUserDetailsRetrieve200Response {
    return UserUserDetailsRetrieve200ResponseFromJSONTyped(json, false);
}

export function UserUserDetailsRetrieve200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserDetailsRetrieve200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : UserUserDetailsRetrieve200ResponseInfoFromJSON(json['info']),
        'certificates': json['certificates'] == null ? undefined : json['certificates'],
        'education': json['education'] == null ? undefined : json['education'],
        'skills': json['skills'] == null ? undefined : json['skills'],
        'projects': json['projects'] == null ? undefined : json['projects'],
    };
}

export function UserUserDetailsRetrieve200ResponseToJSON(json: any): UserUserDetailsRetrieve200Response {
    return UserUserDetailsRetrieve200ResponseToJSONTyped(json, false);
}

export function UserUserDetailsRetrieve200ResponseToJSONTyped(value?: UserUserDetailsRetrieve200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': UserUserDetailsRetrieve200ResponseInfoToJSON(value['info']),
        'certificates': value['certificates'],
        'education': value['education'],
        'skills': value['skills'],
        'projects': value['projects'],
    };
}

