/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUserDetailsRetrieve200ResponseInfo
 */
export interface UserUserDetailsRetrieve200ResponseInfo {
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    zipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUserDetailsRetrieve200ResponseInfo
     */
    country?: string | null;
}

/**
 * Check if a given object implements the UserUserDetailsRetrieve200ResponseInfo interface.
 */
export function instanceOfUserUserDetailsRetrieve200ResponseInfo(value: object): value is UserUserDetailsRetrieve200ResponseInfo {
    return true;
}

export function UserUserDetailsRetrieve200ResponseInfoFromJSON(json: any): UserUserDetailsRetrieve200ResponseInfo {
    return UserUserDetailsRetrieve200ResponseInfoFromJSONTyped(json, false);
}

export function UserUserDetailsRetrieve200ResponseInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserDetailsRetrieve200ResponseInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function UserUserDetailsRetrieve200ResponseInfoToJSON(json: any): UserUserDetailsRetrieve200ResponseInfo {
    return UserUserDetailsRetrieve200ResponseInfoToJSONTyped(json, false);
}

export function UserUserDetailsRetrieve200ResponseInfoToJSONTyped(value?: UserUserDetailsRetrieve200ResponseInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'image_url': value['imageUrl'],
        'address': value['address'],
        'city': value['city'],
        'state': value['state'],
        'zip_code': value['zipCode'],
        'country': value['country'],
    };
}

