/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {number}
   * @memberof User
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof User
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  token: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  phoneNumer?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  address?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  city?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  state?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  zipCode?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  country?: string | null;
  /**
   *
   * @type {Date}
   * @memberof User
   */
  readonly createdAt: Date;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("firstName" in value) || value["firstName"] === undefined) return false;
  if (!("lastName" in value) || value["lastName"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("token" in value) || value["token"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json);
}

export function UserFromJSONTyped(json: any): User {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    firstName: json["first_name"],
    lastName: json["last_name"],
    email: json["email"],
    token: json["token"],
    phoneNumer: json["phone_numer"] == null ? undefined : json["phone_numer"],
    address: json["address"] == null ? undefined : json["address"],
    city: json["city"] == null ? undefined : json["city"],
    state: json["state"] == null ? undefined : json["state"],
    zipCode: json["zip_code"] == null ? undefined : json["zip_code"],
    country: json["country"] == null ? undefined : json["country"],
    createdAt: new Date(json["created_at"]),
  };
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json);
}

export function UserToJSONTyped(
  value?: Omit<User, "id" | "created_at"> | null
): any {
  if (value == null) {
    return value;
  }

  return {
    first_name: value["firstName"],
    last_name: value["lastName"],
    email: value["email"],
    token: value["token"],
    phone_numer: value["phoneNumer"],
    address: value["address"],
    city: value["city"],
    state: value["state"],
    zip_code: value["zipCode"],
    country: value["country"],
  };
}
