/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLoggedIn
 */
export interface UserLoggedIn {
    /**
     * 
     * @type {number}
     * @memberof UserLoggedIn
     */
    idUser: number;
}

/**
 * Check if a given object implements the UserLoggedIn interface.
 */
export function instanceOfUserLoggedIn(value: object): value is UserLoggedIn {
    if (!('idUser' in value) || value['idUser'] === undefined) return false;
    return true;
}

export function UserLoggedInFromJSON(json: any): UserLoggedIn {
    return UserLoggedInFromJSONTyped(json, false);
}

export function UserLoggedInFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoggedIn {
    if (json == null) {
        return json;
    }
    return {
        
        'idUser': json['id_user'],
    };
}

export function UserLoggedInToJSON(json: any): UserLoggedIn {
    return UserLoggedInToJSONTyped(json, false);
}

export function UserLoggedInToJSONTyped(value?: UserLoggedIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id_user': value['idUser'],
    };
}

