# Generated by Django 5.2 on 2025-06-10 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeDevelopment",
            fields=[
                (
                    "id_code_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CssDevelopment",
            fields=[
                (
                    "id_css_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HtmlDevelopment",
            fields=[
                (
                    "id_html_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JavascriptDevelopment",
            fields=[
                (
                    "id_javascript_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id_project", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CertificateDevelopment",
            fields=[
                (
                    "id_certificate_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="codedevelopment",
            name="id_css",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portiq_server.cssdevelopment",
            ),
        ),
        migrations.CreateModel(
            name="EducationDevelopment",
            fields=[
                (
                    "id_education_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GithubDataDevelopment",
            fields=[
                (
                    "id_github_data_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HobbyDevelopment",
            fields=[
                (
                    "id_hobby_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="codedevelopment",
            name="id_html",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portiq_server.htmldevelopment",
            ),
        ),
        migrations.AddField(
            model_name="codedevelopment",
            name="id_javascript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portiq_server.javascriptdevelopment",
            ),
        ),
        migrations.CreateModel(
            name="LanguageDevelopment",
            fields=[
                (
                    "id_language_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherDevelopment",
            fields=[
                (
                    "id_other_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDevelopment",
            fields=[
                (
                    "id_project_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id_project_link",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceDevelopment",
            fields=[
                (
                    "id_reference_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillDevelopment",
            fields=[
                (
                    "id_skill_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id_skill", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                ("id_reference", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portiq_server.user"
            ),
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                ("id_other", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id_language", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                ("id_hobby", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GithubData",
            fields=[
                ("id_github_data", models.AutoField(primary_key=True, serialize=False)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("github_url", models.CharField(blank=True, max_length=255, null=True)),
                ("public_repos", models.IntegerField(blank=True, null=True)),
                ("followers", models.IntegerField(blank=True, null=True)),
                ("following", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id_education", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary_school", "Primary School"),
                            ("high_school", "High School"),
                            ("faculty", "Faculty"),
                            ("course", "Course"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id_certificate", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfoDevelopment",
            fields=[
                (
                    "id_user_info_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioTemplate",
            fields=[
                (
                    "id_portfolio_template",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        max_length=255,
                    ),
                ),
                (
                    "id_certificate_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.certificatedevelopment",
                    ),
                ),
                (
                    "id_education_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.educationdevelopment",
                    ),
                ),
                (
                    "id_github_data_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.githubdatadevelopment",
                    ),
                ),
                (
                    "id_hobby_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.hobbydevelopment",
                    ),
                ),
                (
                    "id_language_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.languagedevelopment",
                    ),
                ),
                (
                    "id_other_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.otherdevelopment",
                    ),
                ),
                (
                    "id_project_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.projectdevelopment",
                    ),
                ),
                (
                    "id_reference_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.referencedevelopment",
                    ),
                ),
                (
                    "id_skill_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.skilldevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
                (
                    "id_user_info_development",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.userinfodevelopment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPortfolioTemplate",
            fields=[
                (
                    "id_user_portfolio_template",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_portfolio_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.portfoliotemplate",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id_work_experience",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperienceDevelopment",
            fields=[
                (
                    "id_work_experience_development",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.codedevelopment",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portiq_server.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="portfoliotemplate",
            name="id_work_experience_development",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portiq_server.workexperiencedevelopment",
            ),
        ),
    ]
