# Generated by Django 5.2 on 2025-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='type',
            field=models.CharField(blank=True, choices=[('primary_school', 'Primary School'), ('high_school', 'High School'), ('faculty', 'Faculty'), ('course', 'Course'), ('workshop', 'Workshop'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
