# Generated by Django 5.1.7 on 2025-03-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0002_projectlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='acquired_skills',
        ),
    ]
