# Generated by Django 5.2 on 2025-05-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0003_alter_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
