# Generated by Django 5.1.7 on 2025-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0003_remove_certificate_acquired_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numer',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
