# Generated by Django 5.1.7 on 2025-03-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0004_rename_phone_numer_user_phone_number_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
