# Generated by Django 5.2 on 2025-05-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0004_alter_other_end_date_alter_other_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
