# Generated by Django 5.1.7 on 2025-04-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0004_language_delete_userskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
