# Generated by Django 5.2 on 2025-05-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0006_workexperience_workexperiencedevelopment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id_reference', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portiq_server.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDevelopment',
            fields=[
                ('id_reference_development', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portiq_server.codedevelopment')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portiq_server.user')),
            ],
        ),
    ]
