# Generated by Django 5.2 on 2025-05-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0008_alter_workexperience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='id_reference_development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portiq_server.referencedevelopment'),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='id_work_experience_development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portiq_server.workexperiencedevelopment'),
        ),
    ]
