# Generated by Django 5.2 on 2025-05-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0009_portfoliotemplate_id_reference_development_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
