# Generated by Django 5.2 on 2025-05-20 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0010_user_github_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubData',
            fields=[
                ('id_github_data', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('number_of_repos', models.IntegerField()),
                ('number_of_followers', models.IntegerField()),
                ('number_of_following', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portiq_server.user')),
            ],
        ),
        migrations.CreateModel(
            name='GithubDataDevelopment',
            fields=[
                ('id_github_data_development', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portiq_server.codedevelopment')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portiq_server.user')),
            ],
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='id_github_data_development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portiq_server.githubdatadevelopment'),
        ),
    ]
