# Generated by Django 5.2 on 2025-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0011_githubdata_githubdatadevelopment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubdata',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='githubdata',
            name='number_of_followers',
        ),
        migrations.RemoveField(
            model_name='githubdata',
            name='number_of_following',
        ),
        migrations.RemoveField(
            model_name='githubdata',
            name='number_of_repos',
        ),
        migrations.AddField(
            model_name='githubdata',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubdata',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubdata',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubdata',
            name='github_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubdata',
            name='public_repos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
