# Generated by Django 5.2 on 2025-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portiq_server', '0012_remove_githubdata_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='id_user',
        ),
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProfessionalSummary',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
