/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Development,
  DevelopmentResponse,
} from '../models/index';
import {
    DevelopmentFromJSON,
    DevelopmentToJSON,
    DevelopmentResponseFromJSON,
    DevelopmentResponseToJSON,
} from '../models/index';

export interface DevelopmentSaveCodeCreateRequest {
    development: Development;
}

/**
 * 
 */
export class DevelopmentApi extends runtime.BaseAPI {

    /**
     */
    async developmentSaveCodeCreateRaw(requestParameters: DevelopmentSaveCodeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DevelopmentResponse>> {
        if (requestParameters['development'] == null) {
            throw new runtime.RequiredError(
                'development',
                'Required parameter "development" was null or undefined when calling developmentSaveCodeCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/development/save-code/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DevelopmentToJSON(requestParameters['development']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DevelopmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async developmentSaveCodeCreate(requestParameters: DevelopmentSaveCodeCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DevelopmentResponse> {
        const response = await this.developmentSaveCodeCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
