/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GithubRequest,
  GithubResponse,
} from '../models/index';
import {
    GithubRequestFromJSON,
    GithubRequestToJSON,
    GithubResponseFromJSON,
    GithubResponseToJSON,
} from '../models/index';

export interface GithubPutGithubReposCreateRequest {
    githubRequest: GithubRequest;
}

/**
 * 
 */
export class GithubApi extends runtime.BaseAPI {

    /**
     */
    async githubDeleteGithubDataDestroyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/github/delete-github-data/`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async githubDeleteGithubDataDestroy(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.githubDeleteGithubDataDestroyRaw(initOverrides);
    }

    /**
     */
    async githubGetGithubDataRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/github/get-github-data/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubResponseFromJSON(jsonValue));
    }

    /**
     */
    async githubGetGithubDataRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubResponse> {
        const response = await this.githubGetGithubDataRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async githubPutGithubReposCreateRaw(requestParameters: GithubPutGithubReposCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubResponse>> {
        if (requestParameters['githubRequest'] == null) {
            throw new runtime.RequiredError(
                'githubRequest',
                'Required parameter "githubRequest" was null or undefined when calling githubPutGithubReposCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/github/put-github-repos/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GithubRequestToJSON(requestParameters['githubRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubResponseFromJSON(jsonValue));
    }

    /**
     */
    async githubPutGithubReposCreate(requestParameters: GithubPutGithubReposCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubResponse> {
        const response = await this.githubPutGithubReposCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
