/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PutSummary,
} from '../models/index';
import {
    PutSummaryFromJSON,
    PutSummaryToJSON,
} from '../models/index';

export interface SummaryGenerateTextUpdateRequest {
    putSummary: PutSummary;
}

/**
 * 
 */
export class SummaryApi extends runtime.BaseAPI {

    /**
     */
    async summaryGenerateTextUpdateRaw(requestParameters: SummaryGenerateTextUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['putSummary'] == null) {
            throw new runtime.RequiredError(
                'putSummary',
                'Required parameter "putSummary" was null or undefined when calling summaryGenerateTextUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/summary/generate-text/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutSummaryToJSON(requestParameters['putSummary']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async summaryGenerateTextUpdate(requestParameters: SummaryGenerateTextUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.summaryGenerateTextUpdateRaw(requestParameters, initOverrides);
    }

}
