/* tslint:disable */
/* eslint-disable */
/**
 * PortIQ API
 * PortIQ API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostVertexAiGenerateText,
  ResponseVertexAiGenerateText,
} from '../models/index';
import {
    PostVertexAiGenerateTextFromJSON,
    PostVertexAiGenerateTextToJSON,
    ResponseVertexAiGenerateTextFromJSON,
    ResponseVertexAiGenerateTextToJSON,
} from '../models/index';

export interface VertexAiGenerateTextCreateRequest {
    postVertexAiGenerateText: PostVertexAiGenerateText;
}

/**
 * 
 */
export class VertexAiApi extends runtime.BaseAPI {

    /**
     */
    async vertexAiGenerateTextCreateRaw(requestParameters: VertexAiGenerateTextCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseVertexAiGenerateText>> {
        if (requestParameters['postVertexAiGenerateText'] == null) {
            throw new runtime.RequiredError(
                'postVertexAiGenerateText',
                'Required parameter "postVertexAiGenerateText" was null or undefined when calling vertexAiGenerateTextCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/vertex-ai/generate-text/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostVertexAiGenerateTextToJSON(requestParameters['postVertexAiGenerateText']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseVertexAiGenerateTextFromJSON(jsonValue));
    }

    /**
     */
    async vertexAiGenerateTextCreate(requestParameters: VertexAiGenerateTextCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseVertexAiGenerateText> {
        const response = await this.vertexAiGenerateTextCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
